import Default from '@layout/Default/Default';
import Page from '@template/SignIn/SignIn';
import { GetServerSideProps } from 'next';
import { getProviders, getSession } from 'next-auth/client';
import Head from 'next/head';

// This is the recommended way for Next.js 9.3 or newer
export const getServerSideProps: GetServerSideProps = async (context) => {
  const providers = await getProviders();
  const session = await getSession(context);

  if (session) {
    return {
      redirect: {
        destination: '/',
        permanent: false,
      },
    };
  }

  return {
    props: { providers },
  };
};

const SignIn = (ssProps) => {
  return (
    <Default>
      <Head>
        <title>Exalos | Sign In</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page ssProps={ssProps} />
    </Default>
  );
};

export default SignIn;
