import Head from 'next/head';

interface Props {
  title?: string;
}

const PageHeaders: React.FC<Props> = ({ title = 'Exalos' }) => {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default PageHeaders;
