import Default from '@layout/Default/Default';
import Page from '@template/Custom404/Custom404';
import Head from 'next/head';

const Planner = () => {
  return (
    <Default>
      <Head>
        <title>Exalos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page />
    </Default>
  );
};

export default Planner;
