import Default from '@layout/Default/Default';
import Index from '@template/Index/Index';
import { GetServerSideProps } from 'next';
import Head from 'next/head';

export const getServerSideProps: GetServerSideProps = async (context) => {
  // context.query -> params
  // service -> getHomePageData()
  return {
    props: {},
  };
};

export default function Home() {
  return (
    <Default>
      <Head>
        <title>Exalos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Index />
    </Default>
  );
}
