import Default from '@layout/Default/Default';
import Page from '@template/Planner/Planner';
import getPlanner from 'app/api/planner/get';
import handleRedirect from 'app/utils/resources/handleRedirect';
import { GetServerSideProps } from 'next';
import { getSession } from 'next-auth/client';
import Head from 'next/head';

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getSession(context);
  if (!session) return handleRedirect('/');

  const plannerData = await getPlanner(session.user.email || '');

  return { props: { planner: plannerData.message || null } };
};

const Planner = (ssProps) => {
  return (
    <Default>
      <Head>
        <title>Exalos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page ssProps={ssProps} />
    </Default>
  );
};

export default Planner;
