import Default from '@layout/Default/Default';
import Page from '@template/Planner/Planner';
import { GetServerSideProps } from 'next';
import Head from 'next/head';

export const getServerSideProps: GetServerSideProps = async (context) => {
  // context.query -> params
  // service -> getHomePageData()
  const sw = await fetch('https://swapi.dev/api/people/1').then((res) => res.json());

  return {
    props: { sw },
  };
};

const Planner = (ssProps) => {
  return (
    <Default>
      <Head>
        <title>Exalos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page />
    </Default>
  );
};

export default Planner;
